version: '3'
services:
  questionbase:
    container_name: qbcontainer
    hostname: questionbase
    image: questionbase
    ports:
      - '8080:8080'
    restart: always
    links:
      - postgres
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: 11060
    ports:
      - "5432:5432"
